// Usage:
//   node scripts/transformMplads.mjs path/to/mplads_export.csv
//
// Reads a real MPLADS works CSV, scores every row with the shared risk
// engine (cost anomaly, same-day batch approvals, duplicate works,
// long-pending heuristic), builds a real SHA-256 hash chain over the
// records, and writes data/realWorks.js + data/realLedger.js.

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import Papa from "papaparse";
import {
  buildGroupStats,
  buildBatchCounts,
  buildDuplicateGroups,
  buildIsolationScores,
  scoreWork,
} from "../lib/riskScoring.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("Usage: node scripts/transformMplads.mjs <path-to-csv>");
  process.exit(1);
}

const raw = fs.readFileSync(inputPath, "utf8");
const parsed = Papa.parse(raw, { header: true, skipEmptyLines: true });

if (parsed.errors.length) {
  console.warn(`Warning: ${parsed.errors.length} rows had parse issues (showing first 3):`);
  parsed.errors.slice(0, 3).forEach((e) => console.warn("  ", e.message, "at row", e.row));
}

const rows = parsed.data
  .map((r) => ({
    ...r,
    sanction_amount: Number(String(r.sanction_amount || "0").replace(/,/g, "")),
    state: (r.state || "").trim(),
    district: (r.nodal_district_per_source || r.district || r.constituency || "").trim(),
    constituency: (r.constituency || "").trim(),
    mp_name: (r.mp_name || "").trim(),
    work_name: (r.work_name || "").trim(),
    implementing_agency_name: (r.implementing_agency_name || "").trim(),
    unique_work_number: (r.unique_work_number || "").trim(),
  }))
  .filter((r) => r.sanction_amount > 0 && r.work_name);

console.log(`Loaded ${rows.length} valid real work records.`);

const stats = buildGroupStats(rows);
const batchCounts = buildBatchCounts(rows);
const duplicateCounts = buildDuplicateGroups(rows);
console.log("Running Isolation Forest over the dataset...");
const mlScores = buildIsolationScores(rows, stats, batchCounts);

const works = rows.map((r, i) => {
  const result = scoreWork(r, stats, batchCounts, duplicateCounts, mlScores[i]);
  return {
    id: r.unique_work_number || `${r.state}-${r.constituency}-${i}`,
    name: r.work_name,
    constituency: r.constituency,
    district: r.district,
    state: r.state,
    contractor: r.implementing_agency_name,
    mp: r.mp_name,
    sanctioned: r.sanction_amount,
    utilized: null,
    score: result.score,
    level: result.level,
    reasons: result.reasons,
    category: result.category,
    dateApproved: r.date_of_administrative_approval,
    status: r.work_status,
    lastUpdated: r.data_as_on || "",
  };
});

let prevHash = "0".repeat(64);
const ledger = works.map((w, i) => {
  const payload = JSON.stringify({ id: w.id, sanctioned: w.sanctioned, status: w.status, prevHash });
  const hash = crypto.createHash("sha256").update(payload).digest("hex");
  const entry = {
    id: i + 1,
    action: "RECORD_IMPORTED",
    work: w.id,
    actor: "MPLADS Data Ingestion",
    hash,
    prevHash,
  };
  prevHash = hash;
  return entry;
});

const outDir = path.join(__dirname, "..", "data");
fs.writeFileSync(
  path.join(outDir, "realWorks.js"),
  `// Auto-generated by scripts/transformMplads.mjs from a real MPLADS export.\n` +
    `export const realWorks = ${JSON.stringify(works, null, 2)};\n`
);
fs.writeFileSync(
  path.join(outDir, "realLedger.js"),
  `// Auto-generated by scripts/transformMplads.mjs. Real SHA-256 hash chain.\n` +
    `export const realLedger = ${JSON.stringify(ledger, null, 2)};\n`
);

const highRisk = works.filter((w) => w.level === "high").length;
const dupCount = works.filter((w) => w.reasons.some((r) => r.label.includes("near-identical"))).length;
console.log(
  `Scored ${works.length} works: ${highRisk} high-risk, ${dupCount} flagged as possible duplicates, ${ledger.length} ledger entries written.`
);
console.log(`Output: data/realWorks.js, data/realLedger.js`);
